apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessus-data
  namespace: tenable-lab
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus
  namespace: tenable-lab
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector: { matchLabels: { app: nessus } }
  template:
    metadata: { labels: { app: nessus } }
    spec:
      containers:
      - name: nessus
        image: tenable/nessus:latest-ubuntu
        ports: [{ containerPort: 8834 }]
        env:
        - { name: USERNAME,        value: "admin" }
        - { name: PASSWORD,        value: "ChangeMe123!" }
        - { name: ACTIVATION_CODE, value: "TU-CODIGO-AQUI" }
        resources:
          requests: { memory: "2Gi", cpu: "1000m" }
          limits:   { memory: "4Gi", cpu: "2000m" }
        volumeMounts:
        - { name: data, mountPath: /opt/nessus }
      volumes:
      - name: data
        persistentVolumeClaim: { claimName: nessus-data }
---
apiVersion: v1
kind: Service
metadata: { name: nessus, namespace: tenable-lab }
spec:
  type: NodePort
  selector: { app: nessus }
  ports:
  - { port: 8834, targetPort: 8834, nodePort: 30834 }